/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pb;

import java.io.FileInputStream;
import java.io.IOException;
import org.lf.pbtutorial.Account;

public class App {
    private static void readFrom(String path) {
        try {
            FileInputStream fs = new FileInputStream(path);
            Account account = Account.parseFrom(fs);
            System.out.println(account);
        } catch(IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        assert (args.length == 1);
        readFrom(args[0]);
    }
}
