# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/login.proto\"\x07\n\x05Token\"A\n\x0bLoginResult\x12\x0f\n\x05\x65rror\x18\x01 \x01(\tH\x00\x12\x17\n\x05token\x18\x02 \x01(\x0b\x32\x06.TokenH\x00\x42\x08\n\x06resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKEN._serialized_start=21
  _TOKEN._serialized_end=28
  _LOGINRESULT._serialized_start=30
  _LOGINRESULT._serialized_end=95
# @@protoc_insertion_point(module_scope)
