# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/product.proto\"m\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.Product.Type\"9\n\x04Type\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\t\n\x05PANTS\x10\x01\x12\t\n\x05SHOES\x10\x02\x12\n\n\x06SHIRTS\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=23
  _PRODUCT._serialized_end=132
  _PRODUCT_TYPE._serialized_start=75
  _PRODUCT_TYPE._serialized_end=132
# @@protoc_insertion_point(module_scope)
